version: "3.7"
services: 
  api:
    image: sample_project/api:0.0.1
    build: 
      context: ./api
    env_file: .env
    ports:
      - 3000
    labels:
      kompose.service.type: nodeport
    depends_on:
     - kvs
  kvs:
    image: redis:6.0-rc1
    ports:
      - 6379
